version: "3.9"
services:
  neo4j:
    image: neo4j:4.4-community
    restart: always
    volumes:
      - neo4j_volume:/data
      - neo4j_volume:/logs
    secrets:
      - my-secret
    ports:
      - 7474:7474
    deploy:
        mode: replicated
        replicas: 1
        endpoint_mode: vip

volumes:
  neo4j_volume:
    external: true

secrets:
  my-secret:
    file: ../../secrets.txt
  
networks:
  default:
    name: net1
    external: true