version: "3.9"
services:
  django:
    image: django:latest
    build: ./
    # ports:
    #   - "8000:8000"
    restart: always
    env_file:
      - ./secret/django.env
networks:
  default:
    name: net1
    external: true