version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:8.3.2
    environment:
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_volume:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.3.2
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_volume:
    external: true

networks:
  default:
    name: net1
    external: true