version: "3.9"
services:
  postgres:
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_PASSWORD=test
    restart: always
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    deploy:
        mode: replicated
        replicas: 1
        endpoint_mode: vip

volumes:
  postgres_volume:
    external: true

networks:
  default:
    name: net1
    external: true