version: "3.9"
services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=test
    restart: always
    # ports:
    #   - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    deploy:
        mode: replicated
        replicas: 1
        endpoint_mode: vip

volumes:
  mariadb_volume:
    external: true

networks:
  default:
    name: net1
    external: true