version: "3.9"
services:
  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - "2368:2368"
    volumes:
      - ghost_volume:/var/lib/ghost/content
    deploy:
        mode: replicated
        replicas: 1
        endpoint_mode: vip

volumes:
  ghost_volume:
    external: true

networks:
  default:
    name: net1
    external: true